token = ${TOKEN}
owner = ${OWNER}
prefix = ${?PREFIX}

success = "🎶"
warning = "💡"
error = "🚫"
loading = "⌚"
searching = "🔎"

game = "DEFAULT"
status = ONLINE
songinstatus = false
altprefix = "NONE"
help = help
npimages = false
stayinchannel = false
maxtime = 0
maxytplaylistpages = 10
skipratio = 0.55
alonetimeuntilstop = 0
playlistsfolder = "Playlists"
updatealerts = true
lyrics.default = "A-Z Lyrics"
loglevel = info
eval = false
evalengine = "Nashorn"
transforms = {}

aliases {
  الاعدادات = [ settings, status ]
  كلمات = [ lyrics ]
  يعمل_الان = [ nowplaying, np, current ]
  شغل = [ play, p ]
  قوائم_التشغيل = [ playlists, pls ]
  القائمة = [ queue, list ]
  حذف = [ remove, delete ]
  بحث_ساوندكلاود = [ scsearch ]
  بحث = [ search, ytsearch ]
  عشوائي = [ shuffle ]
  تخطي = [ skip, voteskip ]
  بريفكس = [ prefix, setprefix ]
  تعيين_دي_جي = [ setdj ]
  تعيين_نسبة_التخطي = [ setskip, setskippercent, skippercent, setskipratio ]
  تعيين_قناة_نصية = [ settc ]
  تعيين_قناة_صوتية = [ setvc ]
  ازالة_اجبارية = [ forceremove, forcedelete, modremove, moddelete, modelete ]
  تخطي_اجباري = [ forceskip, modskip ]
  نقل_مقطع = [ movetrack, move ]
  ايقاف_مؤقت = [ pause ]
  تشغيل_التالي = [ playnext ]
  نوع_القائمة = [ queuetype ]
  تكرار = [ repeat ]
  تخطي_الى = [ skipto, jumpto ]
  ايقاف = [ stop, leave ]
  مستوى_الصوت = [ volume, vol ]
}
